#!/usr/bin/env python3
"""
csv2yolo.py - Convert component coordinates from CSV to YOLO format

This script reads the components.csv file generated by getComponents.py
and converts the coordinates to YOLO format. It parses the KiCad PCB file
to determine the board dimensions and normalizes coordinates relative to
the PCB center.

YOLO format:
- class_id center_x center_y width height
- All values are normalized (0 to 1) relative to image/PCB dimensions
- center_x, center_y are the center of the bounding box
- width, height are the dimensions of the bounding box
"""

import os
import re
import csv
import argparse
from pathlib import Path


def parse_pcb_dimensions(filepath):
    """
    Parse a KiCad PCB file to extract board dimensions from Edge.Cuts layer.
    
    Args:
        filepath: Path to the .kicad_pcb file
        
    Returns:
        Tuple of (min_x, max_x, min_y, max_y, center_x, center_y, width, height)
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find all gr_line and gr_arc elements on Edge.Cuts layer
    edge_cuts_pattern = r'\(gr_(?:line|arc|rect|circle|poly)\s+.*?\(layer\s+"Edge\.Cuts"\).*?\)'
    edge_elements = re.findall(edge_cuts_pattern, content, re.DOTALL)
    
    all_points = []
    
    for element in edge_elements:
        # Extract start points
        start_matches = re.findall(r'\(start\s+([\d.-]+)\s+([\d.-]+)\)', element)
        for match in start_matches:
            all_points.append((float(match[0]), float(match[1])))
        
        # Extract end points
        end_matches = re.findall(r'\(end\s+([\d.-]+)\s+([\d.-]+)\)', element)
        for match in end_matches:
            all_points.append((float(match[0]), float(match[1])))
        
        # Extract mid points (for arcs)
        mid_matches = re.findall(r'\(mid\s+([\d.-]+)\s+([\d.-]+)\)', element)
        for match in mid_matches:
            all_points.append((float(match[0]), float(match[1])))
        
        # Extract center points (for circles)
        # For circles, the 'end' point gives us a point on the circumference
        center_matches = re.findall(r'\(center\s+([\d.-]+)\s+([\d.-]+)\)', element)
        if center_matches:
            # The end point was already added above, which is sufficient for bounding box
            pass
    
    if not all_points:
        raise ValueError("No Edge.Cuts elements found in PCB file")
    
    # Calculate bounding box
    x_coords = [p[0] for p in all_points]
    y_coords = [p[1] for p in all_points]
    
    min_x = min(x_coords)
    max_x = max(x_coords)
    min_y = min(y_coords)
    max_y = max(y_coords)
    
    # Calculate center and dimensions
    center_x = (min_x + max_x) / 2
    center_y = (min_y + max_y) / 2
    width = max_x - min_x
    height = max_y - min_y
    
    return min_x, max_x, min_y, max_y, center_x, center_y, width, height


def read_components_csv(csv_path):
    """
    Read component data from CSV file.
    
    Args:
        csv_path: Path to the components.csv file
        
    Returns:
        List of component dictionaries
    """
    components = []
    
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Convert string values to floats
            component = {
                'name': row['name'],
                'center_x': float(row['center_x']),
                'center_y': float(row['center_y']),
                'bbox_center_x': float(row['bbox_center_x']),
                'bbox_center_y': float(row['bbox_center_y']),
                'width': float(row['width']),
                'height': float(row['height'])
            }
            components.append(component)
    
    return components


def convert_to_yolo_format(components, pcb_width, pcb_height, pcb_center_x, pcb_center_y, class_mapping=None):
    """
    Convert component coordinates to YOLO format.
    
    Args:
        components: List of component dictionaries
        pcb_width: Width of the PCB in mm
        pcb_height: Height of the PCB in mm
        pcb_center_x: Center X coordinate of the PCB
        pcb_center_y: Center Y coordinate of the PCB
        class_mapping: Optional dictionary mapping component names to class IDs
        
    Returns:
        List of YOLO format strings
    """
    yolo_annotations = []
    
    # If no class mapping provided, create a simple one based on unique component names
    if class_mapping is None:
        unique_names = sorted(set(c['name'] for c in components))
        class_mapping = {name: idx for idx, name in enumerate(unique_names)}
    
    for component in components:
        # Get class ID
        class_id = class_mapping.get(component['name'], 0)
        
        # Use bbox_center for YOLO center (this is the actual bounding box center)
        bbox_center_x = component['bbox_center_x']
        bbox_center_y = component['bbox_center_y']
        bbox_width = component['width']
        bbox_height = component['height']
        
        # Normalize coordinates relative to PCB dimensions
        # YOLO format expects center coordinates relative to image origin (top-left usually)
        # But KiCad uses a coordinate system where we need to consider the PCB bounding box
        # We'll normalize to [0, 1] range based on the PCB dimensions
        
        # Calculate PCB origin (top-left corner)
        pcb_origin_x = pcb_center_x - pcb_width / 2
        pcb_origin_y = pcb_center_y - pcb_height / 2
        
        # Calculate normalized center coordinates (relative to PCB origin)
        norm_center_x = (bbox_center_x - pcb_origin_x) / pcb_width
        norm_center_y = (bbox_center_y - pcb_origin_y) / pcb_height
        
        # Calculate normalized dimensions
        norm_width = bbox_width / pcb_width
        norm_height = bbox_height / pcb_height
        
        # Ensure values are within [0, 1] range (clamp if necessary)
        norm_center_x = max(0.0, min(1.0, norm_center_x))
        norm_center_y = max(0.0, min(1.0, norm_center_y))
        norm_width = max(0.0, min(1.0, norm_width))
        norm_height = max(0.0, min(1.0, norm_height))
        
        # Format: class_id center_x center_y width height
        yolo_line = f"{class_id} {norm_center_x:.6f} {norm_center_y:.6f} {norm_width:.6f} {norm_height:.6f}"
        yolo_annotations.append(yolo_line)
    
    return yolo_annotations, class_mapping


def write_yolo_annotation(annotations, output_path):
    """
    Write YOLO annotations to a file.
    
    Args:
        annotations: List of YOLO format strings
        output_path: Path to output annotation file
    """
    with open(output_path, 'w', encoding='utf-8') as f:
        for annotation in annotations:
            f.write(annotation + '\n')
    
    print(f"Written {len(annotations)} annotations to {output_path}")


def write_class_mapping(class_mapping, output_path):
    """
    Write class mapping to a file.
    
    Args:
        class_mapping: Dictionary mapping component names to class IDs
        output_path: Path to output file
    """
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# Class ID to Component Name Mapping\n")
        f.write("# Format: class_id: component_name\n\n")
        
        # Sort by class ID
        sorted_mapping = sorted(class_mapping.items(), key=lambda x: x[1])
        for name, class_id in sorted_mapping:
            f.write(f"{class_id}: {name}\n")
    
    print(f"Written class mapping to {output_path}")


def main():
    """Main function to convert CSV to YOLO format."""
    parser = argparse.ArgumentParser(
        description='Convert component coordinates from CSV to YOLO format'
    )
    parser.add_argument(
        '--csv',
        type=str,
        help='Path to components.csv file (default: scr/input/components.csv)'
    )
    parser.add_argument(
        '--pcb',
        type=str,
        help='Path to .kicad_pcb file (default: first .kicad_pcb in scr/input/)'
    )
    parser.add_argument(
        '--output',
        type=str,
        help='Path to output YOLO annotation file (default: scr/input/annotations.txt)'
    )
    parser.add_argument(
        '--classes',
        type=str,
        help='Path to output class mapping file (default: scr/input/classes.txt)'
    )
    
    args = parser.parse_args()
    
    # Define default paths
    script_dir = Path(__file__).parent
    input_dir = script_dir / 'input'
    
    # Determine CSV path
    if args.csv:
        csv_path = Path(args.csv)
    else:
        csv_path = input_dir / 'components.csv'
    
    # Determine PCB path
    if args.pcb:
        pcb_path = Path(args.pcb)
    else:
        pcb_files = list(input_dir.glob('*.kicad_pcb'))
        if not pcb_files:
            print(f"Error: No .kicad_pcb files found in {input_dir}")
            return
        pcb_path = pcb_files[0]
    
    # Determine output paths
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = input_dir / 'annotations.txt'
    
    if args.classes:
        classes_path = Path(args.classes)
    else:
        classes_path = input_dir / 'classes.txt'
    
    print(f"Reading PCB file: {pcb_path.name}")
    
    # Parse PCB dimensions
    try:
        min_x, max_x, min_y, max_y, center_x, center_y, width, height = parse_pcb_dimensions(pcb_path)
        print(f"PCB Dimensions:")
        print(f"  Bounding Box: ({min_x:.2f}, {min_y:.2f}) to ({max_x:.2f}, {max_y:.2f})")
        print(f"  Center: ({center_x:.2f}, {center_y:.2f})")
        print(f"  Size: {width:.2f} x {height:.2f} mm")
    except Exception as e:
        print(f"Error parsing PCB file: {e}")
        return
    
    print(f"\nReading components from: {csv_path.name}")
    
    # Read components
    try:
        components = read_components_csv(csv_path)
        print(f"Found {len(components)} components")
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return
    
    # Convert to YOLO format
    print("\nConverting to YOLO format...")
    yolo_annotations, class_mapping = convert_to_yolo_format(
        components, width, height, center_x, center_y
    )
    
    # Write YOLO annotations
    write_yolo_annotation(yolo_annotations, output_path)
    
    # Write class mapping
    write_class_mapping(class_mapping, classes_path)
    
    print(f"\nConversion complete!")
    print(f"Found {len(class_mapping)} unique component types")
    
    # Display sample annotations
    print("\nSample YOLO annotations (first 5):")
    print("-" * 80)
    print("Format: class_id center_x center_y width height")
    print("-" * 80)
    for i, annotation in enumerate(yolo_annotations[:5]):
        parts = annotation.split()
        class_id = int(parts[0])
        # Find component name for this class
        component_name = next((name for name, cid in class_mapping.items() if cid == class_id), 'Unknown')
        print(f"{annotation}  # {component_name}")
    print("-" * 80)


if __name__ == '__main__':
    main()
